color added on fail

diff --git a/.github/workflows/notify-teams.yml b/.github/workflows/notify-teams.yml
--- a/.github/workflows/notify-teams.yml
+++ b/.github/workflows/notify-teams.yml
@@ -16,6 +16,7 @@ jobs:
     - name: Print the hello message
       run: |
         echo "Hello World!"
+        exit 1
 
     - name: 📣 Send teams notification
       uses: simbo/msteams-message-card-action@latest
@@ -38,7 +39,7 @@ jobs:
         webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
         title: Pipeline name (Insights copilot Dev Pipeline)
         message: >
-          <p>Dev deployment has failed.
+          <p>Dev deployment has <span style="color: #008000;">failed.</span>
           <br>Please find the issue details here and proceed to create Hotfix branch</p>
         buttons: |
           Failure logs ${{ steps.set_url.outputs.url }}
